import { Category, PageData } from "./types";

export const PAGES: PageData[] = [
  {
    id: 0,
    category: Category.INTRO,
    title: "零售的核心：最后一公里",
    description: "说出你所熟悉的零售企业。它们是如何无缝进入你的生活的？",
    details: "零售（Retail）是指将商品或服务直接销售给最终消费者的商业活动。它是连接生产文明与生活欲望的桥梁。想象你困在荒岛，拥有一堆金条却买不到一瓶水，零售的缺失让价值归零。",
    bgColor: "#0a0a0a",
  },
  {
    id: 1,
    category: Category.HISTORY,
    isTransition: true,
    title: "第一章：零售简史",
    description: "从远古的集市到指尖的触达，零售业经历了数千年的演变。",
    bgColor: "#1a1a1a",
  },
  {
    id: 2,
    category: Category.HISTORY,
    title: "物物交换：诚信的萌芽",
    description: "在货币出现之前，人们如何通过交换多余物资来生存？",
    details: "公元前3000年，美索不达米亚的牧羊人阿卡德用两只羊换取了一个储粮罐。这是零售最原始的形态，建立在彼此需求与诚信的基础之上。4D提示：模拟干草与泥土的气味，感受远古集市的喧嚣。",
    bgColor: "#1a1a0a",
  },
  {
    id: 3,
    category: Category.HISTORY,
    title: "百货商店：欲望的宫殿",
    description: "工业革命带来了大规模生产，宏伟的百货大楼如何改变了城市的中心？",
    details: "1852年，巴黎“乐蓬马歇”诞生。创始人布西科允许顾客“只逛不买”，并引入了退换货制度。华丽的穹顶与橱窗展示，让购物从生存需求变成了一种社交与审美活动。4D提示：高级香水味。",
    bgColor: "#2a2a2a",
  },
  {
    id: 4,
    category: Category.HISTORY,
    title: "自助超市：零售的革命",
    description: "自助购物模式的诞生，如何彻底改变了人与商品的关系？",
    details: "1916年，克拉伦斯·桑德斯开办了第一家 Piggly Wiggly。顾客第一次可以走进货架亲自挑选商品，而不是隔着柜台等待伙计。这种“自助”模式极大地降低了人工成本，提升了购物自由度。",
    bgColor: "#1e293b",
  },
  {
    id: 5,
    category: Category.HISTORY,
    title: "连锁超市：规模的奇迹",
    description: "标准化与规模化如何让零售效率实现了质的飞跃？",
    details: "随着自助模式的成熟，沃尔玛、家乐福等巨头通过强大的供应链和连锁经营，将低价优质商品带给千家万户。零售从“单店竞争”进化到了“体系竞争”。",
    bgColor: "#0f172a",
  },
  {
    id: 6,
    category: Category.HISTORY,
    title: "电子商务：无界的比特",
    description: "互联网打破了地域限制，鼠标一点，商品如何飞越千山万户？",
    details: "从亚马逊的车库包裹到全球包邮，零售进入了数据驱动的极速时代。淘宝、京东等平台开启了全民网购时代，物流成为核心竞争力。4D提示：无人机掠过的强风感。",
    bgColor: "#1e3a8a",
  },
  {
    id: 7,
    category: Category.HISTORY,
    title: "新零售：数智化融合",
    description: "线上线下深度融合，大数据与 AI 如何让零售变得更懂你？",
    details: "无人超市、直播带货、即时配送。零售不再受场景限制，随时随地发生。盒马鲜生等新物种通过全息投影与AI导购，正在重塑人类的消费体验。",
    bgColor: "#312e81",
  },
  {
    id: 8,
    category: Category.IMPACT,
    isTransition: true,
    title: "第二章：行业作用",
    description: "零售业不仅是买卖，更是国民经济的“晴雨表”与“蓄水池”。",
    bgColor: "#064e3b",
  },
  {
    id: 9,
    category: Category.IMPACT,
    title: "反哺产业：农业重塑",
    description: "零售如何作为农业的“指挥棒”，指导农场精准种植？",
    details: "案例：生鲜零售巨头通过消费数据反馈，告诉农民上海人喜欢更甜的草莓。农场据此引进了以色列滴灌技术，实现了精准种植，大幅减少了库存积压与资源浪费。",
    bgColor: "#064e3b",
  },
  {
    id: 10,
    category: Category.IMPACT,
    title: "推动物流：城市神经网络",
    description: "为了更快送达，零售业如何倒逼物流技术实现跨越式升级？",
    details: "自动化仓储、配送无人机、区块链溯源。商品流、资金流在城市群中穿梭，构成了现代商业文明的脉动。零售业是前沿科技的最佳实验场。",
    bgColor: "#0f172a",
  },
  {
    id: 11,
    category: Category.IMPACT,
    title: "促进就业：蓄水池效应",
    description: "零售业如何吸纳多元劳动力，成为社会稳定的“蓄水池”？",
    details: "案例：某偏远小镇建立大型物流中心后，数千名原本赋闲的村民转型为月入过万的数智化分拣员。从导购、收银到快递员、数据分析师，零售业创造了数以亿计的岗位。",
    bgColor: "#334155",
  },
  {
    id: 12,
    category: Category.IMPACT,
    title: "拉动经济：晴雨表",
    description: "零售额如何直接反映人民生活水平，拉动经济增长？",
    details: "消费是拉动经济增长的第一动力。零售业的繁荣带动了整个产业链的良性循环。零售额的波动直接反映了国民经济的健康状况与人民生活的幸福指数。",
    bgColor: "#450a0a",
  },
  {
    id: 13,
    category: Category.THEORY,
    isTransition: true,
    title: "第三章：经典理论",
    description: "掌握零售演化的底层逻辑，洞察商业帝国的兴衰更替。",
    bgColor: "#1e1b4b",
  },
  {
    id: 14,
    category: Category.THEORY,
    title: "零售轮转理论",
    description: "新业态为何总是以低价切入，随后又被更高效的业态所替代？",
    details: "新业态以低价、低毛利进入市场，通过效率优势挑战传统巨头。随后，它并非仅仅因为自身成本上升而衰落，而是被成本更低、效率更高的新业态所替代，形成周而复始的商业转轮。",
    bgColor: "#1e1b4b",
  },
  {
    id: 15,
    category: Category.THEORY,
    title: "零售手风琴理论",
    description: "零售业态为何在“综合性”与“专业性”之间交替循环？",
    details: "模型演示：能量手风琴在扩张（综合）与收缩（专业）间切换。案例：从什么都卖的杂货铺到只卖美妆的丝芙兰，再到集合了生活方式的超级购物中心，零售业态如手风琴般拉伸收缩。",
    bgColor: "#2e1065",
  },
  {
    id: 16,
    category: Category.FUTURE,
    isTransition: true,
    title: "终章：未来已来",
    description: "开启你的创想，定义下一个十年的零售新范式。",
    bgColor: "#020617",
  },
  {
    id: 17,
    category: Category.FUTURE,
    title: "未来已来：终极讨论",
    description: "脑机接口购物、元宇宙零售……十年后的零售店会是什么样子？",
    details: "讨论：如果意念可以直接下单，物理空间还有必要吗？我们在虚拟世界买的是像素还是情感？请分组讨论并开启你的终极创想。",
    bgColor: "#020617",
  },
];
